---
title: "What is Cognition?"
description: |
  This is the first post of this new blog! I will be introducing myself and discussing what I think cognition is.
author:
  - name: Donnan (Chris) Gravelle 
    url: https://donnangravelle.github.io/Blog/
    affiliation: College of Staten Island/CUNY Graduate Center
    affiliation_url: https://www.csi.cuny.edu
date: 08-27-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

```
# Biography
My name is Chris Gravelle, but all my friends call me Donnan. I graduated from Saint John's University in 2019 with a BA in Philosophy. I then attended the University of Edinburgh's Mind, Language, and Embodied Cognition MSc, which I completed in Summer 2020. During that program I completed a dissertation titled "An Ecological Theory of Concepts" where I formulated a theory of affordance weighting and low level sensorimotor categorization based on models of affordance competition. I am currently a student at the CUNY Graduate Center in the Cognitive and Comparative Psychology PhD training program.

## What is Cognition

When I was an undergraduate in philosophy, I asked my mentor what he thought "thinking" was. He laughed and said that he didn't want to tell me. All he said was that "thinking" was some sort of "mental event", and then let me off to go figure it out for myself. What follows are the product of a year of "thinking" about the topic. They are more like rambling than coherent points, and they are the offspring of my philosophical studies as well as some of the experimental work I've been researching. 

There are several ways to define cognition. Behaviorism attempted to define it in terms of observable behaviors. I sympathize with this type of radical empiricism, but it is now obvious that it is too limited in scope to be a full account of cognition.

Chomsky had a great deal to do with the dismantling of Behaviorism. With the postulation of non-observable rules that govern the transformation of stimuli, Chomsky popularized the notion of cognitive representations. However, I don't credit Chomksy with 'creating' cognitive psychology in the sense that we know of it today. Rather, I think the philosopher Jerry Fodor, with the publication of his famous book "The Language of Thought", really set the tone for how cognitive psychology would be perceived by academia. Here he posited a multitude of representations that are propositionally structured, such that they resemble public language. Cognition, on this account, became understood as the transformations of representations that follow syntactic rules of combination, and serve as an intermediary between perception and action. Cognition became entrenched in what the philosopher Susan Hurley called the "Input-Output Picture". A perception tokens a series of cognitive representations that then go through some transformations (what transformations, it is not known), and the end representation produces an action. Thus, my action of going to the fridge to get a beer is a explained by the presence of the representations of BEER and FRIDGE, and the representations being in the right relation to each other. 

This might sound too flowery and armchair for your liking, but this is taken very seriously in many circles of cognitive psychology. For example, Susan Carey, a leader in the field of concept acquisition, fully endorses the language of thought view of concepts and cognition, and she is not alone. 

But what of perception, memory, executive functions, and other topics that are prototypical examples part of cognitive psychology? Well, it is not clear how they are connected to the notion of cognition as the computational transformation of cognitive representations. For example, Fodor claimed that perception and cognition are two separate things. Perception does not interact directly with cognition, and cognition cannot adjust or interfere with perception. If that is the case then, perhaps perception should not be a part of cognitive psychology. After all, is perceiving is not considered a form of thinking, and cognition is synonymous with thinking, then perception is not a field for cognitive psychologists to worry about. 

The view of cognition as the process of transforming sensory information into discrete symbols can severely limit the tools that cognitive psychologists have at their disposal. I don't doubt that there are something like representations in the brain, but I seriously doubt that they are the same type of representations that cognitive psychologists like Carey believe that they are.

Well, what else is left? If cognition is not purely the manipulation of mental symbols, and cognition cannot be explicated in terms of pure behavioral output, then what is cognition? Neural computations might work, but it isn't completely clear that tracking the patterns of neural activation will do everything a psychologist wants them to do. First of all, that is neuroscience or neuropsychology, not cognitive psychology. To say that all thinking can be described in the language of neuroscience is to claim that psychology is purley descriptive, and cannot explain anything. Rather, it can just make lists of functions that neuroscientists explain. 

Thus, the mind is just another way to describe the brain. Of course, that ignores that every organism with a brain has a body. Surely this fact isn't just a contingent truth. There must be something important about bodies that house brains and the environment that they are in.

4E cognition was a response to Fodor-style takes on cognition. Starting with the ecological maxims of J.J. Gibson, inspired by the early American Pragmatists William James and John Dewey, and drawing on recent work in cognitive science, 4E cognition claimed that cognition was Embedded, Embodied, Extended, and Enactive. In other words, cognition is an active process. It is something we do; an action. Thinking is the active navigation in an environment, and spans brain, body, and world. 

The work of linguist George Lackoff and philosopher Mark Johnson on conceptual metaphor and image schemas provided a body based way to get to higher order thought. This sparked the cognitive linguistics paradigm, claimed that language was shaped by the way we think, and the way we think is shaped by the types of bodily experiences we have. Thus, perception and cognition are not two different things. To perceive is to think. Others, like psychologist Kevin O'Regan, who is most famous for his work on change blindness, claim that perception is a type of action. 

The closely related "Active Perception" paradigm in vision claims that vision is not passive, but proactively scans the environment for relevant information related to the goals of the agent. More neuroscientists have denied that the brain is anything like a computer, casting doubt on informational theories of cognition that work under the computer metaphor of the mind. On such a view, cognition is active, embodied, and embedded in an environment and phylogenetic history. 

## Conclusion: A multifaceted approach
So what is cognition? Well it should be rather obvious that I am very much sympathetic to the 4E account of cognition. However, it cannot be the whole answer. Until recently, 4E cognitivists ignored the brain and had nothing to say about it. That is obviously incorrect, the brain needs a full story on any account. They also often deny any representations. This is also wrongheaded in my opinion. It is difficult to make sense of anything in psychology or neuroscience without some form of information storage. 

So what we have left is a mixture of perspectives on the nature of cognition, and I think they all have something important to add. Overt behavior should be considered an indispensable aspect of thinking. When I describe why I got beer from the fridge, I need not make reference to some stored representation. Beliefs can be manifestations of actions, and that is as good of a candidate for thinking as any other. Sensorimotor simulation and abstract concepts can be described in representational terms, and even the most embodied takes on complex concepts (such as the conceptual blending of Fauconnier and Turner) seem to make little sense without antecedant representations. And thinking without doing makes little sense. Thinking either just is, or is for, doing. 

So that is my answer. Thinking consists of the diverse activities that a mind completes in the service of successful navigation in its environment. This can be abstract computations over representations, physical behavior, or interaction with the world. "Thinking", or "Cognition", does not have to be just one thing. I don't think cognitive psychology acts like it does in practice, but yet it seems that the shadow of a single definition for "Cognition" still looms over large in the field, as well as in layman society. 